# JVM args for the Gradle daemon.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Build speed.
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX.
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin.
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
